facture_homepage:
    path:     /facture/index
    defaults: { _controller: FactureBundle:Default:index }

facture_add:
    path:     /facture/add
    defaults: { _controller: FactureBundle:Default:add }

facture_save:
    path:    /facture/save
    defaults: { _controller: FactureBundle:Default:save }
    options:
        expose: true
    methods: [POST]

facture_show:
    path:     /facture/show/{id}
    defaults: { _controller: FactureBundle:Default:show }
    options:
        expose: true
    methods: [GET]

facture_pdf:
    path:     /facture/pdf/{id}
    defaults: { _controller: FactureBundle:Default:pdf }
    options:
        expose: true
    methods: [GET]

facture_consultation:
    path:     /facture/consultation
    defaults: { _controller: FactureBundle:Default:consultation }

facture_list:
    path:    /facture/list
    defaults: { _controller: FactureBundle:Default:list }
    options:
        expose: true
    methods: [POST]

facture_creer_definitif:
    path:     /facture/creer-definitif/{id}
    defaults: { _controller: FactureBundle:Default:creerDefinitif }
    options:
        expose: true
    methods: [GET]

facture_produit_save:
    path:    /facture/produit/save
    defaults: { _controller: FactureBundle:FactureProduit:save }
    options:
        expose: true
    methods: [POST]

facture_produit_show:
    path:     /facture/produit/show/{id}
    defaults: { _controller: FactureBundle:FactureProduit:show }
    options:
        expose: true
    methods: [GET]

facture_service_save:
    path:    /facture/service/save
    defaults: { _controller: FactureBundle:FactureService:save }
    options:
        expose: true
    methods: [POST]

facture_service_show:
    path:     /facture/service/show/{id}
    defaults: { _controller: FactureBundle:FactureService:show }
    options:
        expose: true
    methods: [GET]

facture_produit_pdf:
    path:     /facture/produit/pdf/{id}
    defaults: { _controller: FactureBundle:FactureProduit:pdf }
    options:
        expose: true
    methods: [GET]